name: Magento246 CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [ self-hosted,Linux,X64,qa ] # 构建运行环境-自托管运行器
    #runs-on: ubuntu-latest # 构建运行环境-GitHub托管的运行器[ubuntu-latest、ubuntu-18.04或ubuntu-20.04，windows-latest、windows-2019或windows-2016，macOS-latest、macOS-11或macOS-10.15]
    environment:
      name: qa

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world! in progress

      # 将git代码同步到qa服务器的项目目录
      - name: Deploy file to Qa Server
        if: github.ref == 'refs/heads/develop' # 对分支进行检测
        run: |
          rsync -azvP --exclude='.git' --exclude='.idea' ${{ secrets.SERVER_PATH }} ${{ secrets.SERVER_PORT }}

