name: Magento246 CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [ self-hosted,Linux,X64,qa ] # 构建运行环境-自托管运行器
    #runs-on: ubuntu-latest # 构建运行环境-GitHub托管的运行器[ubuntu-latest、ubuntu-18.04或ubuntu-20.04，windows-latest、windows-2019或windows-2016，macOS-latest、macOS-11或macOS-10.15]

    steps:
      - name: Checkout
      - uses: actions/checkout@v3

      - name: Deploy to Server
        uses: AEnterprise/rsync-deploy@v1.0
        env:
          DEPLOY_KEY: ${{ secrets.SERVER_KEY }}
          ARGS: -avz --delete --exclude='*.env' --exclude='runtime/'
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          FOLDER: ./
          SERVER_IP: ${{ secrets.SERVER_HOST }}
          USERNAME: ${{ secrets.SERVER_USERNAME }}
          SERVER_DESTINATION: ${{ secrets.SERVER_PATH }}
